from server.graph.state import AuditState
from typing import Literal
from server.logging.logger import logging
from server.exception.exception import CustomException
from langchain_core.prompts import ChatPromptTemplate
from server.core.prompts import ALIGNER_PROMPT
import sys
from langchain_core.output_parsers import StrOutputParser

# Main Aligner function
def aligner(state:AuditState ,llm ):
    try:
        """Aligner generates main AUDIT report based on current code and intermediate report generated by reporter"""
        logging.info('Entered aligner node and started generating main audit report')
        # Retrieving reporter draft audit report
        reporter_audit_report = state['reporter_audit_report']
                
        # Retrieving current code
        current_code = state['current_code']
        
        # Defining aligner prompt template
        aligner_prompt = ChatPromptTemplate.from_template(ALIGNER_PROMPT)
        
        # Defining aligner _chain
        aligner_chain = aligner_prompt | llm | StrOutputParser()
        
        # Retrieving aligner audit report
        aligner_response = aligner_chain.invoke({'current_code':current_code,'intermediate_report':reporter_audit_report})
        logging.info('Successfully generated main audit report')
        
        return {'aligner_audit_report':aligner_response}
    except Exception as e:
        logging.info(f'Error while generating main report {str(e)}')
        raise CustomException(e,sys)

